### ISSUE TITLE
Corrupted PDF on production, fine on local

### ISSUE THREAD

**Issue by Francismori7** [stefanzweifel/sidecar-browsershot#104]
Hey there,

I've been using this package for a while now and today, I've noticed that when I generate a PDF from my local dev env, it works fine, however as soon as I generate it from prod, it generated a 2MB PDF file (instead of 540KB), and is corrupted.
Both are running on AWS just fine...

Wondering what I could do to diagnose this? Here is attached the corrupted PDF.
[carte-CC7972778.pdf](https://github.com/stefanzweifel/sidecar-browsershot/files/13462140/carte-CC7972778.pdf)
Mime type of it tells me `application/octet-stream`...

**Comment by Francismori7** [comment]
Further: oddly enough, using `->save()` and saving the file to the local filesystem works just fine and can then properly be attached to an email.

**Comment by stefanzweifel** [comment]
Thanks for raising this @Francismori7. Have to take a closer look at that file as well.

Can you share some pseudo-code on how you generated that corrupted PDF? Which exact methods have you been calling?
This will make debugging and the investigation much much easier.

**Comment by Francismori7** [comment]
Of course:

```php
    public function build()
    {
        $html = view('promotional-cards.print', ['card' => $this->card, 'noAutoPrint' => true])
            ->render();

        $pdf = BrowsershotLambda::html($html)
            ->showBackground()
            ->format('Letter')
            ->addChromiumArguments([
                'font-render-hinting' => 'none',
                'force-color-profile' => 'srgb',
            ])
            ->waitUntilNetworkIdle()
            ->pdf();

        // Force mailgun settings.
        force_corporate_email_settings();

        return $this
            ->from('info@corporate.com', 'Corporate')
            ->subject('Votre carte privilège Corporate!')
            ->attachData($pdf, "carte-{$this->card->number}.pdf", ['mime' => 'application/pdf'])
            ->markdown('mail.promotional-cards.send-card-to-customer')
            ->onQueue('default');
    }
```

This is the exact code, redacted from corporate information that started to fail recently. I can also provide the alternative that worked, that is using `->save()` and saving the PDF file locally instead of using `->pdf()` to only get the data itself.

**Comment by benholmen** [comment]
We ran into this same issue. We generate open graph images and when trying to take the output from browsershot into our media library, got this error:
```
Unsupported image type application/octet-stream. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.
```

Our error started occurring when we upgraded `spatie/browsershot` from v3.59 to v3.60 - we did not upgrade the `wnx/sidecar-browsershot` package. I suspect there's a regression in `spatie/browsershot` - not sure if that package needs to change, or this one.

Our short term solution was to lock `spatie/browsershot` to `3.59`. We're going to upgrade once this issue has been resolved.

Thanks for this great package!

**Comment by stefanzweifel** [comment]
@benholmen Thanks for those notes! Will make finding the root cause a bit easier.

Haven't gotten around to investigate this issue. Rather busy lately. :/

**Comment by stefanzweifel** [comment]
Can confirm that PDF generation is broken. Our test suite on `main` fails due to issues with PDF testing.
https://github.com/stefanzweifel/sidecar-browsershot/actions/runs/7105666909/job/19343371637#step:7:28

Couldn't figure out yet, where the actual problem is.

**Comment by Francismori7** [comment]
> Can confirm that PDF generation is broken. Our test suite on `main` fails due to issues with PDF testing. https://github.com/stefanzweifel/sidecar-browsershot/actions/runs/7105666909/job/19343371637#step:7:28
> 
> Couldn't figure out yet, where the actual problem is.

Feels like we now need to go into ˋ->resultsˋ to fetch the raw response?

**Comment by stefanzweifel** [comment]
I've fixed this issue in #105 a created a new release: https://github.com/stefanzweifel/sidecar-browsershot/releases/tag/v1.13.1.

Let me know if you run into any further issues.

**Comment by mrhn** [comment]
we just upgraded to 1.13.1 and had the same problem as @benholmen downgraded to browsershot 3.59.x and it fixed it. So it would seem the problem is still there.

**Comment by bobwurtz** [comment]
@mrhn Thank you for posting your solution! This fixed it for me.

Same issue/setup as described. I am using `v1.13` and downgrading to Browsershot `v3.59` fixed it for me. Had no issues locally before downgrading, but I was getting corrupt PNG files in production.
